# Generated by Django 6.1.1 on 2026-10-06 07:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, geography=True, null=True, srid=4326)),
                ('acq_datetime', models.DateTimeField(db_index=True)),
                ('brightness', models.FloatField(blank=True, null=True)),
                ('frp', models.FloatField(blank=True, help_text='Fire radiative power (MW)', null=True)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('satellite', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-acq_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, geography=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_cpcb_station', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='OpenAQ / CPCB station id', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AQIGridPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, geography=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('aqi', models.FloatField()),
                ('pm25_estimate', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='airquality__timesta_37e158_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('predicted_aqi', models.FloatField()),
                ('actual_aqi', models.FloatField()),
                ('abs_error', models.FloatField(editable=False)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='airquality.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GroundReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('aqi', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='openaq', max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_readings', to='airquality.location')),
            ],
            options={
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('location', 'timestamp'), name='uniq_ground_loc_ts')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('tropomi', 'TROPOMI'), ('insat', 'INSAT')], default='tropomi', max_length=20)),
                ('no2_column', models.FloatField(blank=True, help_text='mol/m2', null=True)),
                ('so2_column', models.FloatField(blank=True, help_text='mol/m2', null=True)),
                ('aerosol_index', models.FloatField(blank=True, null=True)),
                ('qa_value', models.FloatField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_readings', to='airquality.location')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='airquality__locatio_20f487_idx')],
            },
        ),
    ]
